# AI
langchain4j:
  open-ai:
    streaming-chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-985397d1eae64abc839a2211b92f8fcd
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
      timeout: 120s
    chat-model:
      base-url: https://api.deepseek.com
      api-key: sk-985397d1eae64abc839a2211b92f8fcd
      model-name: deepseek-chat
      log-requests: true
      log-responses: true
      max-tokens: 8192
      strict-json-schema: true
      response-format: json_object
      timeout: 120s
# 添加 COS 对象存储配置（需要从腾讯云获取）
cos:
  client:
    host: codegenerateplatform-1424449475.cos.ap-shanghai.myqcloud.com
    secretId:
    secretKey:
    region: ap-shanghai
    bucket: codegenerateplatform -1424449475
# Pexels 图片搜索配置
pexels:
  api-key: <Your API Key>
# 阿里云 DashScope 配置
dashscope:
  api-key: <Your API Key>
  image-model: wan2.2-t2i-flash


